# Generated by Django 6.0.5 on 2026-05-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('experience', models.CharField(max_length=50, unique=True)),
                ('min_days', models.BigIntegerField(default=0)),
                ('max_days', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Tenure',
                'verbose_name_plural': 'Tenures',
                'db_table': 'tenure',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accrual_rate', models.FloatField(default=0.0)),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accrualmanagement.tenure')),
            ],
            options={
                'verbose_name': 'Accrual Rate',
                'verbose_name_plural': 'Accrual Rates',
                'db_table': 'accrual_rate',
                'abstract': False,
            },
        ),
    ]
