# Generated by Django 6.0.5 on 2026-05-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accrualmanagement', '0001_initial'),
        ('leavemanagement', '0002_remove_leavebalance_pay_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='tenure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accrualmanagement.tenure'),
        ),
        migrations.CreateModel(
            name='AccrualStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('fixed', 'fixed'), ('variable', 'variable')], max_length=20)),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leavemanagement.leavetype')),
            ],
            options={
                'verbose_name': 'Accrual Strategy',
                'verbose_name_plural': 'Accrual Strategies',
                'db_table': 'accrual_strategy',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accrual',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accrualmanagement.accrualstrategy'),
        ),
    ]
