# Generated by Django 6.0.5 on 2026-05-22 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizationmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Employee Type',
                'verbose_name_plural': 'Employee Types',
                'db_table': 'employee_type',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pay Frequency',
                'verbose_name_plural': 'Pay Frequency',
                'db_table': 'pay_frequency',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'db_table': 'employee_profile',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeemanagement.employeetype')),
                ('pay_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeemanagement.payfrequency')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationmanagement.unit')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeemanagement.role')),
            ],
            options={
                'verbose_name': 'Profile Template',
                'verbose_name_plural': 'Profle Templates',
                'db_table': 'profile_template',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenure', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.employeeprofile')),
                ('profile_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.profiletemplate')),
            ],
            options={
                'verbose_name': 'Job Profile',
                'verbose_name_plural': 'Job Profles',
                'db_table': 'job_profile',
                'abstract': False,
            },
        ),
    ]
