# Generated by Django 6.0.5 on 2026-05-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='name',
        ),
    ]
