# Generated by Django 6.0.5 on 2026-05-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0001_initial'),
        ('organizationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profiletemplate',
            unique_together={('role', 'unit', 'employee_type', 'pay_frequency')},
        ),
    ]
