# Generated by Django 6.0.5 on 2026-05-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0002_alter_profiletemplate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='profile_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_profile_template', to='employeemanagement.profiletemplate'),
        ),
    ]
