# Generated by Django 6.0.5 on 2026-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0003_alter_jobprofile_profile_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
