# Generated by Django 6.0.5 on 2026-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0004_alter_jobprofile_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletemplate',
            name='early_clock_in_buffer_min',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profiletemplate',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
