# Generated by Django 6.0.5 on 2026-05-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pay Period',
                'verbose_name_plural': 'Pay Periods',
                'db_table': 'pay_period',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PunchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clock_in', models.DateTimeField(db_index=True)),
                ('clock_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.employeeprofile')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.jobprofile')),
                ('pay_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punchmanagement.payperiod')),
            ],
            options={
                'verbose_name': 'Punch Entry',
                'verbose_name_plural': 'Punch Entries',
                'db_table': 'punch_entry',
                'abstract': False,
                'indexes': [models.Index(fields=['employee', '-clock_in'], name='punch_entry_employe_c74b40_idx')],
            },
        ),
    ]
