# Generated by Django 6.0.5 on 2026-05-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeemanagement', '0002_remove_employeeprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(db_index=True)),
                ('clock_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.employeeprofile')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.jobprofile')),
            ],
            options={
                'verbose_name': 'Punch Entry',
                'verbose_name_plural': 'Punch Entries',
                'db_table': 'punch_entry',
                'indexes': [models.Index(fields=['employee', '-clock_in'], name='punch_entry_employe_c74b40_idx')],
            },
        ),
    ]
