# Generated by Django 6.0.5 on 2026-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0004_alter_jobprofile_end_date'),
        ('punchmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='punchentry',
            name='punch_entry_employe_c74b40_idx',
        ),
        migrations.AddIndex(
            model_name='punchentry',
            index=models.Index(fields=['job_profile', '-clock_in'], name='punch_entry_job_pro_d3891d_idx'),
        ),
        migrations.RemoveField(
            model_name='punchentry',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='punchentry',
            name='pay_period',
        ),
    ]
