# Generated by Django 6.0.5 on 2026-05-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchmanagement', '0002_punchentry_created_at_punchentry_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pay Period',
                'verbose_name_plural': 'Pay Periods',
                'db_table': 'pay_period',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='punchentry',
            name='pay_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punchmanagement.payperiod'),
        ),
    ]
