# Generated by Django 6.0.5 on 2026-05-22 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizationmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allowedIP', models.GenericIPAddressField(unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizationmanagement.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiosk Device',
                'verbose_name_plural': 'Kiosk Devices',
                'db_table': 'kiosk',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KioskToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('validity', models.TextField(choices=[('ALWAYS', 'Always'), ('TIMED', 'Timed')], max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to revoke the access from this kiosk')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicemanagement.kiosk')),
            ],
            options={
                'verbose_name': 'Kiosk Token',
                'verbose_name_plural': 'Kiosk Tokens',
                'db_table': 'kiosk_token',
                'abstract': False,
            },
        ),
    ]
