# Generated by Django 6.0.5 on 2026-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='index',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
