# Generated by Django 6.0.5 on 2026-05-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationmanagement', '0002_unit_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allowedIP', models.GenericIPAddressField(unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizationmanagement.department')),
            ],
            options={
                'verbose_name': 'Kiosk Device',
                'verbose_name_plural': 'Kiosk Devices',
                'db_table': 'kiosk',
                'abstract': False,
            },
        ),
    ]
