# Generated by Django 6.0.5 on 2026-05-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationmanagement', '0003_kiosk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kiosk',
        ),
    ]
