# Generated by Django 6.0.5 on 2026-05-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('max_credit', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pay Code',
                'verbose_name_plural': 'Pay Codes',
                'db_table': 'pay_code',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.FloatField()),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.jobprofile')),
                ('pay_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_code', to='leavemanagement.paycode')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balance',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeoffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.jobprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavemanagement.paycode')),
            ],
            options={
                'verbose_name': 'Time off request',
                'verbose_name_plural': 'Time off requests',
                'db_table': 'timeoff_request',
                'abstract': False,
            },
        ),
    ]
