# Generated by Django 6.0.5 on 2026-05-27 16:13

import django.core.validators
import django.db.models.deletion
import leavemanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0005_profiletemplate_early_clock_in_buffer_min_and_more'),
        ('leavemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='pay_code',
        ),
        migrations.RemoveField(
            model_name='timeoffrequest',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='document',
            field=models.FileField(blank=True, help_text='Upload a document proof if required (only image or pdf)', null=True, upload_to=leavemanagement.models.TimeoffRequest.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])], verbose_name='Document Proof'),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('overflow_leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overflow_to_type', to='leavemanagement.leavetype')),
                ('parent_leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_type', to='leavemanagement.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'db_table': 'leave_type',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amout', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(choices=[('accurated', 'accurated'), ('deducted', 'deducted'), ('reset', 'reset'), ('overflow', 'overflow'), ('borrowed', 'borrow')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.jobprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavemanagement.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Ledger',
                'verbose_name_plural': 'Leave Ledgers',
                'db_table': 'leave_ledger',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_balance_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_hours_per_request', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_days_per_request', models.IntegerField(blank=True, null=True)),
                ('max_requests_per_year', models.IntegerField(blank=True, null=True)),
                ('requires_documentation', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_configuration', to='leavemanagement.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Configuration',
                'verbose_name_plural': 'Leave Configurations',
                'db_table': 'leave_configuration',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='leavemanagement.leavetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leavemanagement.leavetype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PayCode',
        ),
    ]
