# Generated by Django 6.0.5 on 2026-05-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycode',
            name='max_credit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
