# Generated by Django 6.0.5 on 2026-05-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0002_remove_employeeprofile_name'),
        ('leavemanagement', '0002_paycode_max_credit_timeoffrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeemanagement.jobprofile'),
        ),
    ]
