# Generated by Django 6.0.5 on 2026-05-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0003_alter_timeoffrequest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='pay_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_code', to='leavemanagement.paycode'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='stauts',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=20),
        ),
    ]
