# Generated by Django 6.0.5 on 2026-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0004_alter_leavebalance_pay_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='stauts',
            new_name='status',
        ),
    ]
